image: "yanivomc/spring-music"
tag: "latest"
containerPort: "8080"

service:
  type: "LoadBalancer"
  port: "8080"
  name: "myappsvc"

Configmap:
  name: "springcm"
  user: "myuser"

Secret:
  name: secret
  pass: "MTIzNA=="

PVC:
  name: "pvcclaim"

StorageClass:
  name: "spring-ebs-slow"
