apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: appspring
        image: {{ .Values.image }} ":" {{ .Values.tag }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
         - name: {{ .Values.Configmap.name }}
           valueFrom:
            secretKeyRef:
             name: {{ .Values.Configmap.User }}
             key: {{ .Values.Configmap.User }}
        env:
         - name: {{ .Values.Secret.name }}
           valueFrom:
           secretKeyRef:
            name: {{ .Values.Configmap.User }}
            key: {{ .Values.Configmap.pass }}
        volumeMounts:
         - name: storage
           mountPath: '/storage'
      volumes:
      - name: storage
        persistentVolumeClaim:
           claimName: {{ .Values.PVC.name }}