apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: appspring
        image: {{ .Values.image }} ":" {{ .Values.tag }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
         - name: MYAPP_USER_NAME
           valueFrom:
            configMapKeyRef:
             name: {{ .Values.Configmap.name }}
             key: {{ .Values.Configmap.user }}
         - name: MYAPP_USER_SECRET 
           valueFrom:
            secretKeyRef:
              name: {{ .Values.Secret.name }}
              key: {{ .Values.Secret.pass }}
        volumeMounts:
         - name: storage
           mountPath: '/storage'
      volumes:
      - name: storage
        persistentVolumeClaim:
           claimName: {{ .Values.PVC.name }}