---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: myapp
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}